### ISSUE TITLE
Remove fixed shot and flag limits and inform client of limits

### ISSUE THREAD

**Issue by blast007** [BZFlag-Dev/bzflag#120]
Let the server allocate the ID as needed and the client grow a vector.
World weapons are already handled like this.
Shot limits should be communicated as a reload parameter for the tank, not a hard limit on the shots in world. 

A server message should exist to tell a player what the shot limits are on the current flag, the server should not have to send chat messages for this. Client GUI should know as well.

(From @JeffM2501)

**Comment by JeffM2501** [comment]
Overall design.

Client will stop keeping a simple list of shots per player that is based on max shots and keep a list of shot slots that only track reloads.
Shots fired will get a temporary local ID and be kept in a local shot list for local players only.
Once a shot is sent to the server, the server allocates a global shot ID and sends the shot out to all players, with the local shot ID attached (slot number).

When a client gets a shot back, it's added to a global shot list on the client and processed as normal. If the shot is for a local player, it's shot slot ID is looked up, and the shot is moved out of the local shot list into the global list. The reload shot slots keep an independent timer for reloads that is independent of the shot, and only based on the flag that was last fired in that slot. This breaks the dependency on shot lifetime and reload.

This way the server can create more shots for the client and just not assign them to a shot slot (since they didn't come from a shot slot). This will allow better custom flags that manipulate shots (such as triple shot) and remove the requirement for the server to do custom logic to assign kills and scores to players.

For shot limits, the initial shot limit will be sent with the flag grant and the client will count down. Shot limit updates will be sent by the server, with the global shot ID that the limit applies to. Local players will keep a small shot history, so that when they get a shot limit update message, they can see how many shots have been fired since the global shot ID that the limit applies to, and compensate.

I am going to remove the "Flags should be able to be added and removed dynamically." from this task, as it's out of scope for shots. I will add it as a new item.
