### ISSUE TITLE
Add shot type to custom flags

### ISSUE THREAD

**Issue by blast007** [BZFlag-Dev/bzflag#124]
Let custom flags send the shot type. Send custom flag info with flag negotiation.

(From @JeffM2501)

**Comment by JeffM2501** [comment]
Plan:
Add shot type/effect to the overall flag definitions, and just hardcore the effects for the default flags.
The custom flags must also set them (default to standard shot so legacy plugins work).
Add a new shot/effect that does NOT shoot a bullet, but still sends a MsgFireShot to the server to allow the API to have some other "on fire" effect, such as create custom shots, or trigger things.

Flag negotiation will be changed to Flag Definition where the flags are simply sent to the client and linked to effects. The client will only know how to implement effects, not specific named flags. This way custom flags can use any single flag effect with a custom name.

Only a single effect is allowed per flag, to prevent unfair combos (no CL + ST since they are separate effects).

**Comment by JeffM2501** [comment]
PR #164 implements this.
