### ISSUE TITLE
Machine Gun never stops firing when mouse wheel is bound to fire

### ISSUE THREAD

**Issue by Ratfink** [BZFlag-Dev/bzflag#165]
When the mouse wheel is bound to fire, e.g. `bind "Wheel Down" down fire`, a KeyUp event is never seen when the player fires with the wheel.  This causes the player to fire ceaselessly when holding the Machine Gun flag, unless they have another way to send a KeyUp for fire.

I propose a solution to this: if the player is holding an MG flag and is currently firing, then another KeyDown event is seen for fire, the player should stop firing.  This would make the wheel toggle between firing and not firing, and would not affect normal buttons that send both KeyUp and KeyDown events.  If this solution is approved by the developers, I would be happy to try my hand at implementing it.

**Comment by JeffM2501** [comment]
I've solved this issue in the master branch that will be released as 2.6. There are no more planed releases in the 2.4.x line.

The proposed solution in the issue report was too specific to MG and the described problem could happen with any command, not just fire. A more robust solution was implemented.

The fixes that were checked in make the wheel up and down events behave exactly like the other mouse buttons, in that the now all generate an "up" event. Since the mouse wheel can not be "held down" like a normal mouse button, the system now always generates 'up' events after the wheel 'down' event, so it behaves exactly like a click of a single frame. This allows the config to bind fire to "Wheel Down" down, and "Wheel Down" up, just like the left mouse button is bound.

MG already has a number of issues where it will fire once per frame and not on a fixed clock. We've already fixed that in the master branch too.
