### ISSUE TITLE
bzflag is not working properly with 3+ monitors

### ISSUE THREAD

**Issue by jose1711** [BZFlag-Dev/bzflag#201]
with 3 monitor setup `bzflag` window flashes and mouse cursor jumps making it really hard to even exit the game. this video illustrates the issue: https://www.youtube.com/watch?v=HTjVPt2RnXs. once all but one displays are disabled (using `xrandr`) `bzflag` can be played.

**Comment by blast007** [comment]
What Linux distribution and distribution version are you running?  What video card and driver/version?  Do all three of your screens have the same resolution?  Does it also happen with two displays or just with three?

**Comment by jose1711** [comment]
> What Linux distribution and distribution version are you running? 

Arch Linux current

> What video card and driver/version?

Nvidia GeForce GTX 750Ti, proprietary driver 430.26

> Do all three of your screens have the same resolution?

no.

```
$ xrandr | grep connected
VGA-0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 509mm x 286mm
DVI-D-0 connected primary 1280x1024+1920+0 (normal left inverted right x axis y axis) 376mm x 301mm
HDMI-0 connected 1440x900+3200+0 (normal left inverted right x axis y axis) 428mm x 255mm

```

> Does it also happen with two displays or just with three?

I disabled `VGA-0` output reducing number of displays to 2 and the issue disappeared.

**Comment by macsforme** [comment]
I have a three-monitor setup as well, comprised of (from left to right) a 1080p monitor in portrait mode, and then two 1080p monitors in landscape mode. In Ubuntu Linux 19.04, when I use the BZFlag version from the snap repository, which uses SDL 1.2 (probably the same as what is in the repositories for other distributions), the window is spread across all three monitors and is very zoomed in with a large portion of the window missing. When I toggle to windowed mode, display options shows this:

![Screenshot from 2019-07-10 23-48-00](https://user-images.githubusercontent.com/4955448/61029773-a0be4700-a370-11e9-9001-50b2d85e63aa.png)

When I compile from source against SDL 2, the window occupies my main monitor only, with the proper resolution and layout, and display options shows this:

![Screenshot from 2019-07-10 23-57-59](https://user-images.githubusercontent.com/4955448/61029821-c9464100-a370-11e9-999f-4a84de952040.png)

This leads me to wonder if this is an SDL 1.2 issue.

@jose1711, can you try compiling the game from source using SDL 2, and tell us if you have a different result? `./configure -help` shows the options needed to do that.

**Comment by jose1711** [comment]
please note that it's already compiled with SDL 2 on my system:
```
$ ldd `which bzflag` | grep -i sdl
	libSDL2-2.0.so.0 => /usr/lib/libSDL2-2.0.so.0 (0x00007f6fff4b3000)
```

**Comment by macsforme** [comment]
@jose1711, would you please compile and run this source file and post the output? This will give us more specific information about your monitor setup that could help us move forward.

[listResolutions.cpp.zip](https://github.com/BZFlag-Dev/bzflag/files/3409276/listResolutions.cpp.zip)

**Comment by jose1711** [comment]
```
Display 0:
	[Current] 1280 x 1024 @ 60Hz (370546692)
	[0] 1280 x 1024 @ 75Hz (370546692)
	[1] 1280 x 1024 @ 60Hz (370546692)
	[2] 1280 x 960 @ 60Hz (370546692)
	[3] 1152 x 864 @ 75Hz (370546692)
	[4] 1024 x 768 @ 75Hz (370546692)
	[5] 1024 x 768 @ 70Hz (370546692)
	[6] 1024 x 768 @ 60Hz (370546692)
	[7] 800 x 600 @ 75Hz (370546692)
	[8] 800 x 600 @ 72Hz (370546692)
	[9] 800 x 600 @ 60Hz (370546692)
	[10] 800 x 600 @ 56Hz (370546692)
	[11] 640 x 480 @ 75Hz (370546692)
	[12] 640 x 480 @ 73Hz (370546692)
	[13] 640 x 480 @ 60Hz (370546692)
Display 1:
	[Current] 1920 x 1080 @ 60Hz (370546692)
	[0] 1920 x 1080 @ 60Hz (370546692)
	[1] 1680 x 1050 @ 60Hz (370546692)
	[2] 1600 x 900 @ 60Hz (370546692)
	[3] 1440 x 900 @ 60Hz (370546692)
	[4] 1280 x 1024 @ 60Hz (370546692)
	[5] 1280 x 720 @ 60Hz (370546692)
	[6] 1024 x 768 @ 60Hz (370546692)
	[7] 800 x 600 @ 60Hz (370546692)
	[8] 640 x 480 @ 60Hz (370546692)
	Unable to get details for display mode 9 of display 1.
```

**Comment by macsforme** [comment]
It seems that SDL is reporting a certain number of resolutions, but it fails when attempting to get details for at least one of them. I would consider this to be an issue between SDL and your operating systems. I am not seeing any indication that this issue lies within our code.

**Comment by jose1711** [comment]
i think the problem might be in the code of `listResolutions.cpp`.
changing this line:
`const auto numDisplayModes = SDL_GetNumDisplayModes(0);`
to
`const auto numDisplayModes = SDL_GetNumDisplayModes(i);`
and recompiling stops error from appearing. the output then looks as follows:
```
Display 0:
	[Current] 1280 x 1024 @ 60Hz (370546692)
	[0] 1280 x 1024 @ 75Hz (370546692)
	[1] 1280 x 1024 @ 60Hz (370546692)
	[2] 1280 x 960 @ 60Hz (370546692)
	[3] 1152 x 864 @ 75Hz (370546692)
	[4] 1024 x 768 @ 75Hz (370546692)
	[5] 1024 x 768 @ 70Hz (370546692)
	[6] 1024 x 768 @ 60Hz (370546692)
	[7] 800 x 600 @ 75Hz (370546692)
	[8] 800 x 600 @ 72Hz (370546692)
	[9] 800 x 600 @ 60Hz (370546692)
	[10] 800 x 600 @ 56Hz (370546692)
	[11] 640 x 480 @ 75Hz (370546692)
	[12] 640 x 480 @ 73Hz (370546692)
	[13] 640 x 480 @ 60Hz (370546692)
Display 1:
	[Current] 1920 x 1080 @ 60Hz (370546692)
	[0] 1920 x 1080 @ 60Hz (370546692)
	[1] 1680 x 1050 @ 60Hz (370546692)
	[2] 1600 x 900 @ 60Hz (370546692)
	[3] 1440 x 900 @ 60Hz (370546692)
	[4] 1280 x 1024 @ 60Hz (370546692)
	[5] 1280 x 720 @ 60Hz (370546692)
	[6] 1024 x 768 @ 60Hz (370546692)
	[7] 800 x 600 @ 60Hz (370546692)
	[8] 640 x 480 @ 60Hz (370546692)
Display 2:
	[Current] 1440 x 900 @ 60Hz (370546692)
	[0] 1440 x 900 @ 75Hz (370546692)
	[1] 1440 x 900 @ 60Hz (370546692)
	[2] 1280 x 1024 @ 75Hz (370546692)
	[3] 1280 x 1024 @ 60Hz (370546692)
	[4] 1280 x 960 @ 60Hz (370546692)
	[5] 1152 x 864 @ 75Hz (370546692)
	[6] 1024 x 768 @ 75Hz (370546692)
	[7] 1024 x 768 @ 70Hz (370546692)
	[8] 1024 x 768 @ 60Hz (370546692)
	[9] 800 x 600 @ 75Hz (370546692)
	[10] 800 x 600 @ 72Hz (370546692)
	[11] 800 x 600 @ 60Hz (370546692)
	[12] 800 x 600 @ 56Hz (370546692)
	[13] 640 x 480 @ 75Hz (370546692)
	[14] 640 x 480 @ 73Hz (370546692)
	[15] 640 x 480 @ 60Hz (370546692)
```

**Comment by macsforme** [comment]
Ah, good catch. My monitors are all the same resolution (and probably have the same number of modes), so I didn’t catch that.

Can you launch in windowed mode with `-window 1024x768` (or something like that), then select a resolution in Display Options, and then see if that makes it work the next time you launch the game normally?

**Comment by jose1711** [comment]
Running with `-window 1024x768`, then selecting this resolution in Display Options, my primary (center) monitor goes blank (black). When I switch to text console and kill the game process, the display is restored. It's really hard to terminate the process from virtual terminal as the mouse is constantly being grabbed.

**Comment by macsforme** [comment]
Running out of ideas on this. It reminds me of the issue with retina MacBooks, where SDL 2 was reporting resolutions that couldn't actually be set, so the screen just kept flashing as the game tried again and again to set the (incorrect) native resolution. Maybe we need to rework the window initialization so that it tries once, then just accepts whatever resolution it's actually given.

@jose1711, any way you can you try temporarily disabling the proprietary NVIDIA driver and see if the issue persists with the nouveau driver? I may be grasping at straws, but in my experience the proprietary NVIDIA driver can cause strange issues (in my case, certain output ports not working, night shift not working, garbled desktop wallpaper on wake from sleep, and intermittent failures to boot, to name a few).

Otherwise, since we can't reproduce the issue on other Linux three-monitor systems, depending on how much effort you're willing to put in to have this issue fixed, we may need you to run modified code to output some information about the window initialization so we can see where the discrepancy occurs.

**Comment by jose1711** [comment]
hey @macsforme i've tested with nouveau driver and the problem is still present. i am willing to provide more information about my system, try test builds, compile and run helper applications etc.

**Comment by atupone** [comment]
> It's really hard to terminate the process from virtual terminal as the mouse is constantly being grabbed.

You can try confine mouse no in Option->Input

**Comment by atupone** [comment]
> I disabled `VGA-0` output reducing number of displays to 2 and the issue disappeared.

Try disabling the last monitor (HDMI-0) instead of VGA-0. I guess the problem is still there

**Comment by atupone** [comment]
Can you try one thing? 
start bzflag in window mode

bzflag -window 600x480
Go to option->Display->ChangeVideoFormat
Then select 1280 x 1024 Enter and play.
Does it work ?

**Comment by macsforme** [comment]
Can you please launch the game in windowed mode and then take a screenshot of the resolutions listed in Options->Display Settings->Change Video Format, and post that screenshot here? We are trying to figure out which display's resolutions are being shown, and whether that matches the screen we expect BZFlag to show up on when shown fullscreen.

**Comment by blast007** [comment]
I have replicated the issue here.  I have a laptop with a 1366x768 internal display and I plugged in an external monitor with a resolution of 2560x1440.  My "Change Video Format" menu listed the resolutions of the internal display.

When I launch the game fullscreen, it displays as a window on the external monitor and flashes between displaying it and not displaying it.  I added some debugging output to the the SDLWindow::create method in SDL2Window.cxx, and it's repeatedly recreating the window.  Attaching a debugger indicated that a resize event is being repeatedly triggered, but with a size of 2560x1440.

I have an SDL2/GLFW test application I had created for testing another issue last year and I'm able to recreate a similar issue there.  When I attempt to start a fullscreen SDL2 application at the native resolution of the internal display, it instead displays on the external monitor (though there it displays on the full size of the display and doesn't have the flashing issue because I'm not handling resize events).  I do, however, receive a resize event for 2560x1440 when I'm requesting 1366x768.  When I drop the size down to a lower resolution (such as 1360x768, another valid resolution of my internal display), it correctly displays on the internal display, and I receive no resize event.

Of note, when I flip my test program to use GLFW, the issue goes away.  This may be a bug in SDL2 with handling multiple monitors of different resolutions.  It may also specifically be an issue when the display we're attempting to use has a lower native resolution, as I didn't see it on my desktop when I had a 1920x1200 primary display with a 1920x1080 secondary display.

**Comment by jose1711** [comment]
Sorry for not providing feedback for a while. Now that @blast007 was able to reproduce it, is there anything else I can help with?

**Comment by blast007** [comment]
It's very likely just a bug in SDL 2.  I tested a couple other games that use SDL 2 and had similar or identical issues.  I'm using SDL 2.0.9 mainly, as that's what is in Debian Buster.  I also tested Debian Bullseye which has 2.0.10, and I compiled and used the latest SDL 2 from their Mercurial repository.  Still seeing the same sort of issues with those versions.  I will finish the test program demonstrating the problem and will pass it along as an SDL bug report.

One possible workaround would be running the game in a resolution lower than the native resolution of first display.  I had luck with at least one of the above versions of SDL running at 1360x768 instead of 1366x768.  So, you'd have to start windowed and then change the resolution in the game.

Another possible workaround would be arranging your displays differently so that the highest resolution display is the "first" display, though that may be impossible due to how the video card decides which ports get priority.  I was able, however, to make the higher resolution display the primary display and then play fullscreen on that display.  It wouldn't change the resolution, but I could play at the native resolution of that display.

Also, to ease recovery while testing, you could have `watch -n 30 killall bzflag` running in the background, which would kill all instances of bzflag every 30 seconds.

**Comment by atupone** [comment]
could someone that have this "3 monitors issue" try to run the game in this way:
SDL_VIDEO_X11_LEGACY_FULLSCREEN=1 bzflag
to know if that fixes it

**Comment by jose1711** [comment]
> SDL_VIDEO_X11_LEGACY_FULLSCREEN=1 bzflag

This results in left-most monitor turning black, mouse is confined within area of primary (center) monitor.

**Comment by atupone** [comment]
and bzflag works ?

**Comment by blast007** [comment]
I have (finally) created a bug report with SDL:
https://bugzilla.libsdl.org/show_bug.cgi?id=4990

**Comment by macsforme** [comment]
If I could get some confirmation whether #251 fixes this issue, that would be fantastic.

**Comment by jose1711** [comment]
I am happy to report that https://github.com/macsforme/bzflag/tree/sdl2_window_fixes branch fixed the problem with BZFlag on my computer. Thanks!
