### ISSUE TITLE
Got shot by Lazer while holding Cloaking

### ISSUE THREAD

**Issue by The-Noah** [BZFlag-Dev/bzflag#211]
Within a split second I grabbed Cloaking and then got shot by Laser, I can see why this happened.

![bzfi0045-cropped](https://user-images.githubusercontent.com/35819660/62428153-d7fbeb80-b6c3-11e9-97e8-065ec8be4603.png)

**Comment by Zehra** [comment]
While this happens quite rarely, lag has been known to make it occur.

**Comment by macsforme** [comment]
> While this happens quite rarely, lag has been known to make it occur.

Good insight. I believe the order would be:

1. Your client sends a message to the server trying to grab the Cloaking flag
2. The server relays you the packet for another player firing at you with Laser
3. The server acknowledges your flag grab and broadcasts that you picked up Cloaking
4. Before your client receives the flag grab acknowledgement, it receives the laser shot packet, which is a hit on your tank, so your client sends a message to the server saying you are dead
5. Your client receives the flag grab acknowledgement, but disregards it because you are dead
6. The server acknowledges your death and broadcasts that you are dead, and also broadcasts your flag drop

There is even a small delay from when you die until your death is shown in your console, so it makes sense that those messages are based on packets from the server, rather than your own local death detection, which seems consistent with the above explanation.

**Comment by The-Noah** [comment]
Sounds like that's what happened. I'm guessing there isn't an easy fix without moving death detection to the server.

**Comment by macsforme** [comment]
This is a known limitation of our protocol at the moment, and is unlikely to change without a major redesign.
