### ISSUE TITLE
Retina scaling broken on macOS (again) in 10.15 Catalina

### ISSUE THREAD

**Issue by macsforme** [BZFlag-Dev/bzflag#245]
I asked for as many details as possible, but here is what we have so far:

> &lt;ashvala> on macOS 10.15, you can't have the full retina scaling 
> &lt;ashvala> for bz, i.e 
> &lt;ashvala> https://www.dropbox.com/s/y2zih1pkehbbf9o/Screen%20Shot%202020-03-14%20at%202.08.58%20AM.png?dl=0 
> &lt;ashvala> this is with the stock bz client. I've tried to compile it and it doesn't make a difference 
> &lt;ashvala> additionally, this is on AMD Radeon 560x. I've tried switching the GPU and it doesn't help
> &lt;ashvala> I have a feeling it might have something to do with macOS Catalina's increasingly awful support for OpenGL, but, I figure it's worth flagging with you

![Screen Shot 2020-03-14 at 2 08 58 AM](https://user-images.githubusercontent.com/4955448/76693241-2e98b300-661f-11ea-819d-e772b081529c.png)

**Comment by TankUp-BZFlag** [comment]
I have the same Problem. This is the reason, why I switched back to Mojave three times. Had this issue with Catalina 15.1, 15.2 and 15.3! I have an iMac retina late 2015, Intel Iris Pro Graphics 6200.

**Comment by macsforme** [comment]
> I have the same Problem. This is the reason, why I switched back to Mojave three times. Had this issue with Catalina 15.1, 15.2 and 15.3! I have an iMac retina late 2015, Intel Iris Pro Graphics 6200.

Any more details you can provide? For example, did the issue appear only on certain display scaling settings and not others? Did the issue exist when BZFlag was in windowed mode? The more details we have about this issue, the better our chances of fixing it, especially because AFAIK none of our developers have regular access to a Mac with a retina display at the moment.

**Comment by TankUp-BZFlag** [comment]
Hi,

The full screen mode works perfectly with exactly half of the resolution of the retina display. Only that looks stupid. The higher I choose the resolution, the more the screen moves down. When I choose full native retina resolution, the image is moved down exactly half of the monitor (as in the screeenshot of this thread). If I switch to windowed mode, I can choose the full retina resolution, but due to the scaling of the window, the appearance suffers, especially from the radar, it all seems very thick. I could test beta versions or send log files, if needed. Only tell me what to do...

**Comment by macsforme** [comment]
Would you please give this build a try and report back whether the issue is resolved? I enabled SDL 2 to allow high DPI windows in this build.

http://fairserve.net/~josh/bzflag/BZFlag-20200402-highDPI-allowed.zip

**Comment by TankUp-BZFlag** [comment]
> Would you please give this build a try and report back whether the issue is resolved? I enabled SDL 2 to allow high DPI windows in this build.
> 
> http://fairserve.net/~josh/bzflag/BZFlag-20200402-highDPI-allowed.zip

I tried your version, but sadly no effect. It's just the same. I tried with our MacBook Air (early2016, Intel HD Graphics 515), too. The same there... :(

**Comment by Stokestack** [comment]
It's not clear from the post what the problem is, but I'm also having major scaling problems on a Retina iMac. If I set BZ's resolution to HD, the image is shifted up so 40% or so is off the top of the screen.

If I hit F1 to window it, then full-screen it with the Mac window-maximize control, it fills the screen as expected.

**Comment by macsforme** [comment]
Could any of you give the official 2.4.20 binary a try, and see if the issue still persists? I was able to semi replicate the issue previously in a hacked up virtual machine, but I cannot anymore after updating to the latest SDL 2 with our 2.4.20 official build. Using an actual retina screen might be different, so I'd like to verify.

**Comment by Stokestack** [comment]
The new version appears to fix it, thanks!

**Comment by blast007** [comment]
I can also confirm it is working correctly here. I'll close out this issue.
