### ISSUE TITLE
brightness changes on dual monitors

### ISSUE THREAD

**Issue by bluecoat58** [BZFlag-Dev/bzflag#300]
Using a dual monitor setup and running bzflag (latest)(SDL 2) causes the non bzflag monitor to increase in brightness a lot. Bzflag is the only full screen app that does this.  Running Linux Mint 20.3

https://termbin.com/697b

**Comment by blast007** [comment]
We're just using SDL_SetWindowBrightness, so this is probably a limitation of the platform or with SDL2.  That SDL function might even get removed in SDL 2.1 since they recommend using shaders for handling brightness adjustments.  If you don't want BZFlag messing up the brightness, just leave the brightness setting at the default in the game.
