### ISSUE TITLE
Flags are not saved with the in-game "Save World" button

### ISSUE THREAD

**Issue by TheGiraffe3** [BZFlag-Dev/bzflag#366]
## Problem Description

When you join to a server and attempt to save the world, the flags are not saved with the map.
If you are trying to run the world locally with bots but not other veteran players (for example Two Tanks) this can be a nuisance, because you have to manually add the flags back in.

## Solution

If possible, change the code that saves the map to also save the flags. I don't suppose it would be too hard.

**Comment by blast007** [comment]
The save world function in the client rebuilds the BZW file based on the binary representation that is sent from the server.  The server doesn't send some information because it's not relevant to the client, so information is going to be lost in the process.  If you want to run a proper copy of a map, you should download the original from the forums or elsewhere, or ask the server owner for a copy.
