### ISSUE TITLE
i beg you please tell how to run the project i want to see output

### ISSUE THREAD

**Issue by BrandedAlok** [BZFlag-Dev/bzflag#97]
i beg you please tell how to run the project i want to see output

**Comment by allejo** [comment]
We're gonna need a lot more information on what exactly you're trying to do. Your OS, what exactly you're trying to run (this repo has a number of projects: bzflag, bzadmin, bzfs, etc.), how are you trying to build things?

We [provide binaries for you to download and use](https://github.com/BZFlag-Dev/bzflag/releases/latest), which I recommend you using.

**Comment by BrandedAlok** [comment]
i have Windows10 Pc and i beg you please tell me to execute any file i want to see the output.just guide me to make any file execute so that i can see output

**Comment by allejo** [comment]
In order to not offend the authors of the READMEs who spent their time writing them,

👉  [Window's README for compilation](https://github.com/BZFlag-Dev/bzflag/blob/2.4/README.WINDOWS) & it's [respective build dependencies](https://github.com/BZFlag-Dev/bzflag-dependencies/releases) and [how to use the dependencies](https://github.com/BZFlag-Dev/bzflag-dependencies#using-the-libraries).

If you have more _specific_ questions, then we'd be happy to help.

**Comment by blast007** [comment]
Our github issues are for reporting and tracking bugs and features, not for general questions.  If you need help building after reading the information that allejo provided, please instead ask on our IRC channel or our forums.

You also seem to be spamming this same kind of ticket to many other projects.
